BKNPET/app/urls.py
from django.urls import path
from .views import acerca_de, home, contacto, acerca_de, registrar, pokebusca, recientes, \
    agregar_producto, modificar_producto, listar_productos, eliminar_producto,   \
    producto1,producto2,producto3,producto4,producto5,producto6,producto7,producto8,registro, \
    adopcion, agregar_mascota, listar_mascota, modificar_mascota, eliminar_mascota, mascota_collection, mascota_element


from rest_framework.urlpatterns import format_suffix_patterns
from app import views



urlpatterns = [
    # APP
    path('', home, name="home"),
    path('contacto/', contacto,name="contacto"),
    path('acerca_de/', acerca_de, name="acerca_de"),
    path('registrar/', registrar, name="registrar"),
    path('pokebusca/', pokebusca, name="pokebusca"),
    path('recientes/', recientes, name="recientes"),
    
    # CRUD
    path('agregar-producto/', agregar_producto, name="agregar_producto"),
    path('listar-producto/', listar_productos, name="listar_producto"),
    path('modificar-producto/<int:id>/', modificar_producto, name="modificar_producto"),
    path('eliminar-producto/<int:id>/', eliminar_producto, name="eliminar_producto"),
    
    # REGISTRO FUNCIONAL
    path('registro/', registro, name="registro"),

    # API LOCAL
    path('api/', views.producto_collection, name='producto_collection'  ),
    path('api/<int:pk>/', views.producto_element, name= 'producto_element' ),
    
    # API MASCOTA
    path('api_mascota/', views.mascota_collection, name='mascota_collection'  ),
    path('api_mascota/<int:pk>/', views.mascota_element, name= 'mascota_element' ),
    
    # APP NUEVA
    path('adopcion/', adopcion, name="adopcion"),
    path('agregar_mascota/', agregar_mascota, name="agregar_mascota"),
    path('listar_mascota/', listar_mascota, name="listar_mascota"),
    path('modificar_mascota/<int:id>/', modificar_mascota, name="modificar_mascota"),
    path('eliminar_mascota/<int:id>/', eliminar_mascota, name="eliminar_mascota"),
    
    # PRODUCTOS
    path('producto1/', producto1, name="producto1"),
    path('producto2/', producto2, name="producto2"),
    path('producto3/', producto3, name="producto3"),
    path('producto4/', producto4, name="producto4"),
    path('producto5/', producto5, name="producto5"),
    path('producto6/', producto6, name="producto6"),
    path('producto7/', producto7, name="producto7"),
    path('producto8/', producto8, name="producto8"),
    
]

urlpatterns = format_suffix_patterns(urlpatterns)

BKNPET/bknpet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView



from bknpet.settings import MEDIA_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # localhost:8000/usuario

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

BKNPET/app/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    imagen = models.ImageField(upload_to="productos", null=True)
    
    def __str__(self):
        return self.nombre
    


# -----------------------------------------------------------------------------------
#                               APP NUEVA
class Mascota(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    raza = models.CharField(max_length=30)
    nombre = models.CharField(max_length=30)
    sexo = models.CharField(max_length=10, null=True)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to="mascotas", null=True)
    
    
    def __str__(self):
        return self.raza

BKNPET/app/templates/ADOP/adopcion.html
{%extends 'app/base.html'%}


{% load static %}
{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'app/css/estilos_1.css'%}">
{% endblock %}

{% block contenido %}
{% load humanize %}
<section>
    <div class="container mt-5 mb-5"> 
        <div class="row justify-content-center">

            {% for m in mascotas %}
            <div class="card mt-4" style="margin-left: 25px; width:15rem;">
                {% if m.imagen %}
                <img class="card-img-top" src="{{ m.imagen.url }}" alt="Card image cap">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ m.categoria | capfirst }}</h5>
                    <h5 class="card-title"> Nombre: {{ m.nombre | title }}</h5>
                    <h6 class="card-title"> Raza: {{ m.raza | title }}</h6>
                    <h6 class="card-title"> Sexo: {{ m.sexo | title }}</h6>
                    <h6 class="card-title">Descripcion: </h6>
                    <p class="card-text">
                        {{ m.descripcion }}
                    </p>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>

{% endblock %}

BKNPET/app/templates/ADOP/agregar_pet.html
{%extends 'app/base.html'%}


{% load static %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    
<link rel="stylesheet" href="{% static 'app/css/estilos_3.css' %}">
<link rel="stylesheet" href="{% static 'app/css/estilos_1.css'%}">
{% endblock %}

{% block contenido %}

{% load crispy_forms_tags %}

<br><br>
<body style="background-image: url({% static 'app/img/krista-mangulsone-9gz3wfHr65U-unsplash.jpg'%})">
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body" style="background-color: #a8a3f7; border-radius: 20px; border: 2px solid white;" >
                <div class="form">
                    <h2 class="titulo " style="color: #4b44db;">Agregar Mascotas</h2>
                    
                    <form method="post" enctype="multipart/form-data"  >
                        <br>
                        <br>

                        {% csrf_token %}
                        {{ form | crispy }}
                        
                        <br>
                        <br>
                        <div class="d-flex justify-content-center ">
                            <input type="reset" name="Cancelar" class="button btn-secondary" style="background-color: #6e67f7;" >
                            <br>
                            <br>
                            <input type="submit" value="Guardar" class="button btn-primary" style="background-color: #6e67f7;">
                        </div>

                    </form>

                    {{mensaje}}
                </div>
            </div>
        </div>
    </div>
</div>
</body>

{% endblock %}

BKNPET/app/templates/ADOP/listar_pet.html
{%extends 'app/base.html'%}

{%  block js %}

<script>
    function eliminar_mascota(id) {
        Swal.fire({
            "title": "¿Estas seguro?",
            "text" : "Esta accion no se puede deshacer",
            "icon" : "question",
            "showCancelButton": true
        })
        .then(function(result){
            if(result.isConfirmed){
                window.location.href = "/eliminar_mascota/"+id+"/"
            }
        })
        
    }
</script>
{% endblock %}



{% load static %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    
<link rel="stylesheet" href="{% static 'app/css/estilos_3.css' %}">
<link rel="stylesheet" href="{% static 'app/css/estilos_1.css'%}">

{% endblock %}

{% block static %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

{% endblock %}

{% block contenido %}
{% load humanize %}

<br><br><br>
<div class="card">
    <div class="card-body">
        <h2>Listado de Mascotas</h2>
        <hr>
        <table class="table table-striped table-hover table-responsive-sm">
            <tr>
                <th>Nombre</th>
                <th>Raza</th>
                <th>Categoria</th>
                <th>Imagen</th>
                <th>Opciones</th>
            </tr>
        
            {% for m in mascotas %}
            <tr>
                <td>{{ m.nombre | title }}</td>
                <td>{{ m.raza | title }}</td>
                <td>{{ m.categoria | title }}</td>
                <td><img src= "/media/{{ m.imagen }}" style="width: 200px; height: 200px"/></td>

                <td>
                    {% if perms.app.change_mascota%}
                    <a href="{% url 'modificar_mascota' m.id %}" class="btn btn-info">Modificar</a>
                    {% endif %}

                    {% if perms.app.delete_producto %}
                    <a href="#" onclick="eliminar_mascota({{m.id}})" class="btn btn-danger">Eliminar</a>
                    {% endif %}
                </td> 

            </tr>
        
            {% endfor %}
        </table>
    </div>
</div>




{% endblock %}

BKNPET/app/templates/ADOP/modificar_pet.html
{%extends 'app/base.html'%}


{% load static %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    
<link rel="stylesheet" href="{% static 'app/css/estilos_3.css' %}">
<link rel="stylesheet" href="{% static 'app/css/estilos_1.css'%}">
{% endblock %}

{% block contenido %}

{% load crispy_forms_tags %}
<body style="background-image: url({% static 'app/img/krista-mangulsone-9gz3wfHr65U-unsplash.jpg'%})"
<br><br>

<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body" style="background-color: #a8a3f7; border-radius: 20px; border: 2px solid white;">
                <div class="form">
                    <h2 class="titulo" style="color: #4b44db;">Editar Mascota</h2>
                    <hr>
                    
                    <form action="" method="post" enctype="multipart/form-data"  >
                        
                        {% csrf_token %}
                        {{ form | crispy }}
                        
                        
                
                        <div class="d-flex justify-content-end ">
                            <input type="reset" name="Cancelar" class="button btn-secondary" style="background-color: #6e67f7;">
                            &nbsp;
                            <input type="submit" value="Editar" class="button btn-primary" style="background-color: #6e67f7;">
                        </div>

                    </form>

                    {{mensaje}}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}